### ISSUE TITLE
Version 2.5.0 beta: Uncaught TypeError, PHP 8, Entry Evaluation->Manage

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#1373]
**Verify the Following**
Reporting About the Latest Version? Yes
**BCOE&M Info**
Version: 2.5.0 beta
Installation URL: 
Hosted Installation? No

**Describe the Bug**
Looks like another PHP 8 restriction. I was going the Entry Evaluations Manage button and it goes to a javascript not enable message.

The error log has this message:
[Sat Nov 12 20:25:49.811007 2022] [php:error] [pid 22512:tid 1836] [client 127.0.0.1:2846] PHP Fatal error:  Uncaught TypeError: date(): Argument #2 ($timestamp) must be of type ?int, string given in E:\\Users\\Jimmy\\Documents\\BCOEM\\git-work\\brewcompetitiononlineentry\\lib\\date_time.lib.php:94\nStack trace:\n#0 E:\\Users\\Jimmy\\Documents\\BCOEM\\git-work\\brewcompetitiononlineentry\\lib\\date_time.lib.php(94): date('m/d/Y', '')\n#1 E:\\Users\\Jimmy\\Documents\\BCOEM\\git-work\\brewcompetitiononlineentry\\eval\\dashboard.eval.php(295): getTimeZoneDateTime('-6', '', '1', '0', 'short', 'date-time')\n#2 E:\\Users\\Jimmy\\Documents\\BCOEM\\git-work\\brewcompetitiononlineentry\\eval\\default.eval.php(3): include('E:\\\\Users\\\\Jimmy\\\\...')\n#3 e:\\Users\\jimmy\\Documents\\BCOEM\\git-work\\brewcompetitiononlineentry\\index.php(302): include('E:\\\\Users\\\\Jimmy\\\\...')\n#4 {main}\n  thrown in E:\\Users\\Jimmy\\Documents\\BCOEM\\git-work\\brewcompetitiononlineentry\\lib\\date_time.lib.php on line 94, referer: https://www.jtestwp.test/bcoem-bluebonnet/index.php?section=admin

**To Reproduce**
1. Go to Admin Dashboard->Scoring->Entry Evaluations->Manage

Thanks.

**Comment by jimmyorkin** [comment]
It was my problem. I had tables defined with invalid location columns.
